### ISSUE TITLE
Tests timeout

### ISSUE THREAD

**Issue by martinboksa** [werk85/node-html-to-text#210]
Hello,
sometimes tests exceed the timeout limit 2000ms ( several times even 3000ms ). In my case, it fails CI jobs where the machine is probably slower.

Would you increase the mocha timeout to 5000/10000ms? 
Thanks

Temporary solution: fork library and set timeout limit in `package.json`
```
"test": "mocha --timeout 10000 && eslint .",
```

**Comment by KillyMXI** [comment]
That must be quite a slow machine indeed.

Can you tell which tests fail due to timeout in your case?

CLI tests are usually slowest. In the long run, CLI should be moved to a separate package, I think. And I can take a look how to increase timeout specifically to CLI tests in the meantime.

Main tests must not take so long. I would rather tune the tests. But I suggest to wait a little and see how these will perform after upcoming update. (Is almost there, could've pushed it today if not busy with other things.)

**Comment by martinboksa** [comment]
Almost always test 'should output nothing with empty input' fail. 

The set of tests is failing.
1 attempt:
![Screenshot 2020-10-14 at 14 12 24](https://user-images.githubusercontent.com/4490694/95987124-493a4100-0e27-11eb-8f43-dbb98ed17c78.png)

2 attempt:
![screenshot_2020-10-14_at_12 27 51](https://user-images.githubusercontent.com/4490694/95987559-e4331b00-0e27-11eb-8fb4-dafec1387d9b.png)

Please, any idea to workaround to disable 'prepare' script in the library?

**Comment by KillyMXI** [comment]
Ok, so it's CLI tests.

I'm going to set the timeout in `test-cli.js` to 5000ms.

I'm also going to change `prepare` to `prepublishOnly` in `package.json`. It seems to be more of a nuisance than a useful thing currently.

**Comment by KillyMXI** [comment]
And it's in master now.
